config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static#landing'

  resources :sessions, controller: "sessions", only: [:new, :create, :destroy, :index]
  resources :users, controller: "users", only: [:create, :update, :show, :destroy, :new] do
  resources :photos
  end

  get "/users/edit/:id" => "users#edit", as: "edit_profile"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/users/fb_login/:id" => "users#fb_login", as: "fb_login"
  post "/users/set_username" => "users#set_username", as: "set_username"
  post "/search" => "users#search", as: "search"
  get "/users/verification/:user_id" => "braintree#new", as: "new_verification"
  post "/users/verification/:user_id" => "braintree#payment", as: "verification"
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController

  def new

    @user = User.find(params[:user_id])
    @client_token = Braintree::ClientToken.generate
    # @user = User.find(params[:id])
  end

  def payment

    @user = User.find(params[:user_id])

  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  result = Braintree::Transaction.sale(
     :amount => "1", #this is currently hardcoded
     :payment_method_nonce => nonce_from_the_client,
     :options => {
       :submit_for_settlement => true
    }
   )
    if result.success?
      @user.update(:verification => 1)
      flash[:success] = "Account successfully verified!"
      redirect_to root_path
    else
      flash[:error] = "Verification was unsuccessful, please try again."
      redirect_to new_verification_path
    end
  end
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/views/braintree/new.html.erb
<h1 class="payment-title">Checkout</h1>
<div class="demo-frame">

     <%= form_for :checkout_form, url: verification_path(@user.id), html: { id: "cardForm"} do |form| %>

       <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>

       <div id="card-number" class="hosted-field"></div>

       <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
       <div id="expiration-date" class="hosted-field"></div>


       <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
       <div id="cvv" class="hosted-field"></div>

       <%= form.hidden_field "payment_method_nonce" %>

       <div class="button-container">
         <%= form.submit "Pay now", disabled: false, class: "btn btn-primary", id: "submit-payment-btn" %>
       </div>
     <% end %>
   </div>

   <!-- Load the Client component. -->
 <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

 <!-- Load the Hosted Fields component. -->
 <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

 <script>
      var form = document.querySelector("#cardForm");
      var submit = document.querySelector("#submit-payment-btn");

      braintree.client.create({
        authorization: '<%= @client_token %>'
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          console.error(clientErr);
          return;
        }

        // This example shows Hosted Fields, but you can also use this
        // client instance to create additional components here, such as
        // PayPal or Data Collector.

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '14px'
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }
          },
          fields: {
            number: {
              selector: '#card-number',
              placeholder: '4111 1111 1111 1111'
            },
            cvv: {
              selector: '#cvv',
              placeholder: '123'
            },
            expirationDate: {
              selector: '#expiration-date',
              placeholder: '10/2019'
            }
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            console.error(hostedFieldsErr);
            return;
          }

          submit.removeAttribute('disabled');

          form.addEventListener('submit', function (event) {
            event.preventDefault();

            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
              }

              // If this was a real integration, this is where you would
              // send the nonce to your server.
              document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
              form.submit();
            });
          }, false);
        });
      });
    </script>