config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static#landing'

  resources :sessions, controller: "sessions", only: [:new, :create, :destroy, :index]
  resources :users, controller: "users", only: [:create, :update, :show, :destroy, :new] do
  resources :photos
  end

  get "/users/edit/:id" => "users#edit", as: "edit_profile"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/users/fb_login/:id" => "users#fb_login", as: "fb_login"
  post "/users/set_username" => "users#set_username", as: "set_username"
  post "/search" => "users#search", as: "search"
  get "/users/verification/:user_id" => "braintree#new", as: "new_verification"
  post "/users/verification/:user_id" => "braintree#payment", as: "verification"
end

app/models/user.rb
class User < ApplicationRecord

  validates :email_address, uniqueness: true, presence: true, :on => :create
  validates :username, uniqueness: true, presence: true, :on => :create
  validates_presence_of :password, :on => :create
  has_secure_password
  mount_uploader :display_picture, DisplayPictureUploader
  has_many :authentications, dependent: :destroy
  has_many :photos, class_name: "Photo", foreign_key: "user_id"

  def self.create_with_auth_and_hash(authentication, auth_hash)

    user = self.create!(
      full_name: auth_hash["extra"]["raw_info"]["name"],
      email_address: auth_hash["extra"]["raw_info"]["email"],
      password: SecureRandom.hex(2),
      username: SecureRandom.hex(2),
        )
        user.authentications << authentication
        return user
      end

      # grab fb_token to access Facebook for user data
  def fb_token
    x = self.authentications.find_by(provider: 'facebook')
      return x.token unless x.nil?
    end

  def self.search(search) # User.search()
    if search
      search_result = User.where("username ILIKE ? OR email_address ILIKE ? OR full_name ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
        if search_result.empty?
          return User.all
        else
          return search_result
        end
    else
      flash[:error] = "Query did not return any matches"
      return User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# before_filter :authorize

  def new

    @user = User.new

  end

  def create

    user = User.new(user_params)

      if user.save
        session[:user_id] = user.id
        flash[:success] = "Your account has been successfully created, complete your profile."
        redirect_to edit_profile_path(user.id)
      else
        flash[:error] = "An error occurred, please try again"
        redirect_to new_user_path
      end

  end


  def fb_login

  end

  def set_username
    @user = current_user
      User.update(@user.id, username: params[:user][:username])
      if @user.save
        redirect_to edit_profile_path(@user.id)
      else
        redirect_to fb_login_path(@user.id)
      end
  end

  def edit

    @user = current_user

  end

  def update


    @user = current_user

    if @user.profile_description.nil?

        User.update(@user.id, full_name: edit_params[:full_name], profile_description: edit_params[:profile_description], display_picture: edit_params[:display_picture])
        @user.display_picture = edit_params[:display_picture]

          if @user.save
            flash[:success] = "Profile completed, please verify your account."
            redirect_to new_verification_path(@user.id)
          else
            flash[:error] = "Changes could not be captured, try again another time. Please proceed to verify your account."
            redirect_to new_verification_path(@user.id)
          end
    else
      User.update(@user.id, full_name: edit_params[:full_name], profile_description: edit_params[:profile_description], display_picture: edit_params[:display_picture])
      @user.display_picture = edit_params[:display_picture]
        if @user.save
          flash[:success] = "Changes saved."
          redirect_to root_path
        else
          flash[:error] = "Changes could not be captured, try again another time."
          redirect_to root_path
    end
  end
end
  def search

    @users = User.search(search_params[:search])

    respond_to do |format|
      format.js
      # if browser does not support .js, the line below provides a html fallback
      # format.html { redirect t}
    end
  end

  private

  def user_params

    params.require(:user).permit(:full_name, :username, :email_address,:password,:password_confirmation)

  end

  def edit_params

    params.require(:user).permit(:full_name, :display_picture, :profile_description)

  end

  def search_params

    params.slice(:search)

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search_results.html.erb
<% if @users == nil %>

<% else %>
  <% @users.each do |result| %>
  <%= image_tag(result.display_picture.url) %>
  <p><%= result.full_name %></p>
  <p><%= link_to "#{result.username}", user_photos_path(result.id) %></p>
  <p><%= result.email_address %></p>
  <%end%>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your Shuttershare profile</h1>

  <% @id = params[:id] %>
<%= form_for @user, url:"/users/#{@id}", method: 'put', :html => {:multipart => true} do |f| %>
    <p>Full Name<%= f.text_field :full_name %></p>
    <p>Profile Description<%= f.text_field :profile_description %></p>
    <p>Display Picture<%= f.file_field :display_picture %></p>
    <p><%= f.submit %></p>
<% end %>

app/views/users/fb_login.html.erb
<h1>Set Username</h1>

<%= form_for :user, url: '/users/set_username', method: :post do |f| %>

Username: <%= f.text_field :username %>
<%= f.submit "Submit"%>

<% end %>

app/views/users/new.html.erb
<div class = "container">
  <div class="col-md-6"><span class="float-left"></span>
	  <div class="wrapper">
        <%= form_for :user, url: '/users', :html => {class: 'form-signin'} do |f| %>
          <h3 class="form-signin-heading">Sign Up</h3>
            Full Name: <%= f.text_field :full_name, type:"text", class:"form-control" %>
            Username: <%= f.text_field :username, type:"text", class:"form-control" %>
            Email: <%= f.text_field :email_address, type:"text", class:"form-control" %>
            Password: <%= f.password_field :password, type:"password", class:"form-control" %>
            Password Confirmation: <%= f.password_field :password_confirmation, type:"password", class:"form-control" %>
            <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block", name: "Submit", type:"Submit"%>
            <div id="links"><%= link_to "Sign in with Facebook", "/auth/facebook" %>
        <% end %>
	   </div>
  </div>
</div>

app/views/users/search.js.erb
$("#feed").remove();
$("#search-results").html("<%= j(render partial: 'search_results', locals: { results: @users}) %>");